server:
  host: localhost
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webshop
    username: postgres
    password: 111111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.springframework:
      web: INFO
      security: INFO